# Generated by Django 3.2.9 on 2021-11-24 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0004_delete_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='habit',
            name='complete',
        ),
        migrations.RemoveField(
            model_name='habit',
            name='created',
        ),
        migrations.RemoveField(
            model_name='habit',
            name='title',
        ),
        migrations.RemoveField(
            model_name='habit',
            name='user',
        ),
        migrations.AddField(
            model_name='habit',
            name='done',
            field=models.CharField(default=False, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='habit',
            name='interval',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='habit',
            name='name',
            field=models.CharField(default=True, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='habit',
            name='qty',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='habit',
            name='url',
            field=models.CharField(default=True, max_length=200),
            preserve_default=False,
        ),
    ]
