# Generated by Django 3.2.9 on 2021-11-24 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0005_auto_20211124_1512'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habit',
            name='qty',
            field=models.IntegerField(),
        ),
    ]
